import { logoutAdminAction } from "@/app/actions/admin-auth.actions";
import { logoutBuyerAction } from "@/app/actions/buyer-auth.actions";
import { getCurrentAdminUser, getCurrentBuyerUser } from "@/lib/auth/session";
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import Link from "next/link";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const adminUser = await getCurrentAdminUser();
  const buyerUser = await getCurrentBuyerUser();
  const secondaryActionClass =
    "rounded-xl border border-slate-300 bg-white px-3 py-1.5 font-medium text-slate-700 shadow-sm transition hover:border-slate-400 hover:bg-slate-50 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-indigo-300";
  const primaryActionClass =
    "rounded-xl border border-indigo-200 bg-indigo-50 px-3 py-1.5 font-medium text-indigo-700 shadow-sm transition hover:border-indigo-300 hover:bg-indigo-100 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-indigo-300";

  return (
    <html lang="es">
      <body
        className={`${geistSans.variable} ${geistMono.variable} min-h-screen bg-slate-50 text-slate-900 antialiased`}
      >
        <header className="sticky top-0 z-40 border-b border-slate-200/80 bg-white/80 backdrop-blur-md">
          <div className="mx-auto flex w-full max-w-6xl items-center justify-between px-4 py-4 sm:px-8">
            <Link
              href="/"
              className="inline-flex items-center gap-2 rounded-lg px-2 py-1 text-sm font-semibold text-slate-900 transition hover:bg-slate-100"
            >
              <span className="inline-block h-2.5 w-2.5 rounded-full bg-indigo-500" />
              Ticketera
            </Link>

            <nav className="flex items-center gap-2.5 text-sm">
              {adminUser ? (
                <>
                  <Link
                    href="/admin"
                    className={primaryActionClass}
                  >
                    Panel admin
                  </Link>
                  <form action={logoutAdminAction}>
                    <input type="hidden" name="next" value="/" />
                    <button
                      type="submit"
                      className={secondaryActionClass}
                    >
                      Salir
                    </button>
                  </form>
                </>
              ) : buyerUser ? (
                <>
                  <Link
                    href="/mi-cuenta"
                    className={primaryActionClass}
                  >
                    Mi cuenta
                  </Link>
                  <form action={logoutBuyerAction}>
                    <input type="hidden" name="next" value="/" />
                    <button
                      type="submit"
                      className={secondaryActionClass}
                    >
                      Salir
                    </button>
                  </form>
                </>
              ) : (
                <>
                  <Link
                    href="/auth/ingresar"
                    className={secondaryActionClass}
                  >
                    Ingresar
                  </Link>
                  <Link
                    href="/auth/registro"
                    className={primaryActionClass}
                  >
                    Crear cuenta
                  </Link>
                </>
              )}
            </nav>
          </div>
        </header>

        {children}
      </body>
    </html>
  );
}
